theme: jekyll-theme-minimal
title: Flanker task
description: This is a browser-based version of the Eriksen flanker task built using jsPsych. Currently it contains two congruent and two incongruent stimuli which are repeated randomly 25 times each.
